### ISSUE TITLE
Deprecated node version in nvmrc

### ISSUE THREAD

**Issue by adneforslund** [netliferesearch/craft-starter#140]
Node 16 is deprecated and it seems like there is a difference between the version set in nvmrc and the one specified in the `engines` object in `package.json`

**Comment by KevinBodi** [comment]
Hei, Ådne! 😄

I've updated the specified Node versions to a much newer stable release and done tests to see if things work and are supported by the specified version.

I will also look into PHP versions, plugin versions, Craft CMS itself and documentation for those who use DDEV in the very near future.
