### ISSUE TITLE
Import lessons from .htaccess pull request into nginx.conf

### ISSUE THREAD

**Issue by nilsnh** [netliferesearch/craft-starter#19]
There's a current [pull request](https://github.com/netliferesearch/craft-starter/blob/a4ff5d8bae285b85da3bb812f8d0f0cb4f1fbf3a/.htaccess) with a .htaccess file. But we're using nginx. It would be great if someone could review the pull request to see if there's some general lessons we can try to import into our nginx.conf.

**Comment by Andersos** [comment]
Looks like there no longer is a pull request. Is this issue solved?

**Comment by nilsnh** [comment]
Hmm. Yeah, let's consider it resolved. 👍
