### ISSUE TITLE
Redis error

### ISSUE THREAD

**Issue by AndreasNaustdal** [netliferesearch/craft-starter#56]
Following the steps in craft starter and Guide: Deploy av Craft CMS til ArcusTech ( https://intranett.netlife.com/frontend-backend-og-cms/guide-deploy-craft-cms-til-arcustech)
is leading to an error. 

Database Exception – yii\db\Exception
Redis error: ERR Client sent AUTH, but no password is set
Redis command was: AUTH

Check redis config in config/app.php

**Comment by nilsnh** [comment]
Fixed in 3b77dc6191567431948b87d5a40749c630c4b02d
