### ISSUE TITLE
Docker does not allow craft to send e-mail

### ISSUE THREAD

**Issue by Baynrich** [netliferesearch/craft-starter#73]
In its current state, the docker setup does not allow craft to send e-mail.

Proposed fix:
Add `EXPOSE 587` to the Dockerfile.
By adding this line I was able to set up a user registration form sending validation e-mails through postmark.

Using port 25 still gave me an error, 587 seems to work.

**Comment by Baynrich** [comment]
![image](https://user-images.githubusercontent.com/19597001/107205100-be94d780-69fd-11eb-9c9b-e0f142ac686a.png)
![image](https://user-images.githubusercontent.com/19597001/107205139-ca809980-69fd-11eb-9f3c-3deea47fa382.png)

Skjermdump fra fungerende oppsett.

**Comment by timharek** [comment]
Closing this because of 233445b.
