### ISSUE TITLE
Bytte Webpack med Vite

### ISSUE THREAD

**Issue by nilsnh** [netliferesearch/craft-starter#99]
_RFC: Request for comments._

Er det nokre nedsider ved å bytte til [Vite](https://vitejs.dev/)? Eg trur det vil gi oss meir fart under utvikling. Eg veit at @svale også er nyfiken på å ta dette i bruk.

Nyttige kjelder: 
- https://nystudio107.com/blog/using-vite-js-next-generation-frontend-tooling-with-craft-cms

**Comment by svale** [comment]
FYI: Jeg har påbegynt en PR på denne som kommer snart...

**Comment by nilsnh** [comment]
Løst i https://github.com/netliferesearch/craft-starter/pull/103 . 🎉
